"""Export a fitted strategy as a folder (and a ZIP) that runs on its own, outside the notebook.

Bundle layout:

    strategy.py              two pure functions: predict_returns and target_weights (generated, see below)
    model.joblib             the fitted model
    config.json              the StrategyConfig, as a plain dictionary
    feature_names.json       the model's feature columns, in order
    manifest.json            provenance: versions, creation time, symbols, reference-or-own knobs
    run_paper.py             the paper-trading runner (a copy)
    README_EXPORT.md         step-by-step instructions for running it at home
    requirements.txt         what to pip install (scikit-learn pinned to the version that fitted the model)
    .env.example             where the PAPER keys go (empty; the real .env is never exported)
    quantsoc_ml/             a copy of this package, so strategy.py computes features with the same code
    data/prices_recent.csv.gz  the last days of the committed snapshot, for the offline demo

strategy.py does not re-implement anything: it calls quantsoc_ml.features.build_features with
the strategy's own feature list and portfolio.weights_from_forecasts, exactly as the research
pipeline did. tests/test_export_paper.py checks that its forecasts equal models.predict_panel's.

Credentials are never written. `.env` is never copied, every text file is scanned for
key-shaped strings, and if APCA keys are set in this process's environment the whole bundle is
scanned for their values (bytes, not just text) before the export is accepted.
"""
from __future__ import annotations

import importlib.util
import json
import os
import re
import shutil
import sys
import types
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Union

import pandas as pd

from . import __version__
from .portfolio import StrategyConfig

PACKAGE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_DIR.parent
BUNDLE_KIND = "quantsoc_ml.strategy_bundle"
SCHEMA_VERSION = 1
RECENT_DATA = "data/prices_recent.csv.gz"
RECENT_DAYS = 300
BUNDLE_FILES = ["strategy.py", "model.joblib", "config.json", "feature_names.json", "manifest.json",
                "run_paper.py", "README_EXPORT.md", "requirements.txt", ".env.example"]
EXCLUDED_PARTS = {".env", "__pycache__", ".ipynb_checkpoints", ".git", ".venv", "venv", ".pytest_cache"}
TEXT_SUFFIXES = (".py", ".json", ".md", ".txt", ".example", ".cfg", ".toml", ".ini", ".csv")
SECRET_PATTERNS = [
    re.compile(r"APCA_API_KEY_ID\s*=\s*['\"]?[A-Z0-9]{16,}"),
    re.compile(r"APCA_API_SECRET_KEY\s*=\s*['\"]?[A-Za-z0-9/+]{30,}"),
    re.compile(r"\b(?:PK|AK)[A-Z0-9]{16,}\b"),                      # Alpaca key ids: PK... paper, AK... live
    re.compile(r"(?i)(secret|api_key|apikey|token)\s*=\s*['\"][A-Za-z0-9/+_\-]{20,}['\"]"),
]

STRATEGY_PY = '''"""Exported strategy: forecasts and target weights, nothing else.

Generated by quantsoc_ml.export on {created}. {source_note}

Both functions are pure: they read their arguments, change nothing, and return a new Series.
They use the quantsoc_ml package (a copy sits next to this file) so the features are computed
by exactly the code the model was trained with.
"""
from __future__ import annotations

from typing import Mapping, Union

import pandas as pd

from quantsoc_ml import features as F
from quantsoc_ml.portfolio import StrategyConfig, weights_from_forecasts


def _config(config: Union[StrategyConfig, Mapping]) -> StrategyConfig:
    return config if isinstance(config, StrategyConfig) else StrategyConfig.from_dict(config)


def predict_returns(prices_wide: pd.DataFrame, volume_wide: pd.DataFrame, model, config) -> pd.Series:
    """Forecast 5-day returns for the LAST date of `prices_wide`, one value per symbol.

    prices_wide / volume_wide: dates down, symbols across (adjusted closes and volumes), with at
    least as many trading days as the longest feature window. When config.rank_features is True
    (the default, and what the research pipeline did) the features are rank-normalised per date
    across the symbols in the table, so pass the same universe the model was trained on. A symbol
    whose features are not all available on the last date gets NaN; target_weights then gives it
    weight 0 (it is neither long nor short), and the paper runner leaves any position you already
    hold in it alone rather than selling on a missing number.
    """
    cfg = _config(config)
    names = list(cfg.feature_names)
    feats = F.build_features(prices_wide, volume_wide, names=names)
    if getattr(cfg, "rank_features", True):
        # Same as training: each feature becomes its rank among the stocks present on that date.
        feats = F.rank_normalise(feats)
    last = feats.index.get_level_values("date").max()
    rows = feats.xs(last, level="date")[names]
    ok = rows.notna().all(axis=1)
    pred = pd.Series(float("nan"), index=rows.index.astype(str), name="forecast")
    if ok.any():
        pred[ok.to_numpy()] = model.predict(rows[ok].to_numpy(dtype=float))
    pred.index.name = "symbol"
    pred.attrs["date"] = str(pd.Timestamp(last).date())
    return pred


def target_weights(predictions: pd.Series, config) -> pd.Series:
    """Long the top n_long forecasts, short the bottom n_short (portfolio.weights_from_forecasts)."""
    cfg = _config(config)
    return weights_from_forecasts(predictions, n_long=cfg.n_long, n_short=cfg.n_short)
'''


# --------------------------------------------------------------------------- secret scanning

def scan_for_secrets(text: str) -> List[str]:
    """Key-shaped strings in `text`, truncated so the report itself never carries a whole key."""
    hits = []
    for pat in SECRET_PATTERNS:
        for m in pat.finditer(text):
            hits.append(m.group(0)[:10] + "...")
    return hits


def _bytes_hits(data: bytes) -> List[str]:
    """Key-shaped strings inside ANY file's bytes (a pickle or joblib holds plain text too)."""
    hits = scan_for_secrets(data.decode("latin-1"))
    for enc in ("utf-16-le", "utf-16-be"):
        try:
            hits += [h + f" ({enc})" for h in scan_for_secrets(data.decode(enc, "ignore"))]
        except Exception:
            pass
    return hits


def _env_secret_values() -> List[bytes]:
    vals = []
    for k in ("APCA_API_KEY_ID", "APCA_API_SECRET_KEY"):
        v = os.environ.get(k)
        if v and len(v) >= 8:
            vals.append(v.encode())
    out = []
    for v in vals:
        out += [v, v.decode('utf-8', 'ignore').encode('utf-16-le'), v.decode('utf-8', 'ignore').encode('utf-16-be')]
    return out


def _scan_dir(out: Path) -> List[str]:
    """Problems found in a written bundle, as safe-to-print strings (never the secret itself)."""
    problems = []
    env_vals = _env_secret_values()
    for p in sorted(out.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(out).as_posix()
        if p.name == ".env" or (p.name.startswith(".env") and p.name != ".env.example"):
            problems.append(f"{rel} is an environment file")
        data = p.read_bytes()
        for h in _bytes_hits(data):
            problems.append(f"{rel}: key-shaped text {h}")
        if any(v in data for v in env_vals):
            problems.append(f"{rel} contains the value of an APCA_* environment variable")
    return problems


# --------------------------------------------------------------------------- export

def _versions() -> Dict[str, str]:
    import joblib
    import numpy
    import sklearn
    return {"python": sys.version.split()[0], "numpy": numpy.__version__, "pandas": pd.__version__,
            "scikit-learn": sklearn.__version__, "joblib": joblib.__version__, "quantsoc_ml": __version__}


def _requirements(versions: Mapping[str, str]) -> str:
    return ("# What run_paper.py needs. scikit-learn is pinned to the version that fitted model.joblib,\n"
            "# because a saved model may not load in a different scikit-learn version.\n"
            "numpy>=1.26,<3\npandas>=2.2,<4\n"
            f"scikit-learn=={versions['scikit-learn']}\n"
            "joblib>=1.3\npython-dotenv>=1.0\nalpaca-py>=0.40,<1\n")


def _source_file(*candidates: Path) -> Path:
    for c in candidates:
        if c.is_file():
            return c
    raise FileNotFoundError(f"cannot find {candidates[0].name} (looked in {', '.join(str(c.parent) for c in candidates)})")


def _prepare_out(out: Path) -> None:
    """Create `out` fresh. Refuses to delete a non-empty folder that is not an earlier bundle."""
    if out.exists():
        if not out.is_dir():
            raise ValueError(f"{out} exists and is not a folder")
        if any(out.iterdir()):
            try:
                kind = json.loads((out / "manifest.json").read_text()).get("bundle_kind")
            except Exception:
                kind = None
            if kind != BUNDLE_KIND:
                raise ValueError(f"{out} is not empty and is not an earlier strategy bundle; choose another folder")
            env_files = [q.name for q in out.iterdir() if q.name.startswith(".env") and q.name != ".env.example"]
            if env_files:
                raise ValueError(f"{out} holds {', '.join(env_files)} from an earlier run; move it out of the folder "
                                 "first (re-exporting replaces the whole folder, and your keys must never be inside it)")
            shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)


def _default_symbols(data_path: Optional[Path]) -> List[str]:
    if data_path is None:
        raise ValueError("pass symbols=[...]: no price snapshot was found to read them from")
    from .data import load_prices
    return sorted(load_prices(data_path)["symbol"].unique().tolist())


def export_bundle(model, config: Union[StrategyConfig, Mapping], out_dir, used_reference: bool = False,
                  symbols: Optional[Sequence[str]] = None, data_path: Optional[Union[str, Path]] = None,
                  recent_days: int = RECENT_DAYS, trained_on: Optional[Sequence[str]] = None) -> Path:
    """Write the bundle folder and return its path.

    `used_reference` is True when any of the five knobs came from the workshop's reference
    solution rather than the participant's own work; the manifest records it and the runner
    prints it. `symbols` defaults to the symbols of the price snapshot. `data_path` (default:
    the committed snapshot) supplies the last `recent_days` trading days for the offline demo;
    pass data_path=False to leave the data out. `trained_on` (for example `train_df.attrs["features"]`)
    is the feature list the model was fitted on; when given it must equal the knobs' list, which
    catches a knob changed after fitting. Without it only the NUMBER of features can be checked.
    """
    import joblib
    from . import data as D

    cfg = (config if isinstance(config, StrategyConfig) else StrategyConfig.from_dict(config)).validate()
    names = list(cfg.feature_names)
    n_in = getattr(model, "n_features_in_", None)
    if n_in is not None and int(n_in) != len(names):
        raise ValueError(f"the model was fitted on {n_in} features but these knobs give {len(names)}: {names}")
    if trained_on is not None and list(trained_on) != names:
        raise ValueError(f"the model was fitted on {list(trained_on)} but these knobs give {names}: "
                         "refit the model after changing a knob")
    if data_path is None:
        try:
            data_path = D.default_path()
        except FileNotFoundError:
            data_path = None
    elif data_path is False:
        data_path = None
    else:
        data_path = Path(data_path)
    syms = sorted(str(s).upper() for s in (symbols or _default_symbols(data_path)))
    if len(syms) <= cfg.n_long + cfg.n_short:
        raise ValueError(f"{len(syms)} symbols cannot hold {cfg.n_long} longs and {cfg.n_short} shorts with room to "
                         "spare: one stock with no data on the day would then stop every run")
    from .paper import rows_needed
    need = rows_needed(names)
    if int(recent_days) < need:
        raise ValueError(f"these features need {need} trading days of history but the bundle ships {recent_days} "
                         f"(recent_days); pass recent_days={need + 20} or use a shorter window")

    out = Path(out_dir)
    _prepare_out(out)
    created = datetime.now(timezone.utc).isoformat(timespec="seconds")
    note = ("Some knobs came from the workshop REFERENCE solution, not only your own work."
            if used_reference else "All five knobs are your own choices.")
    versions = _versions()

    (out / "strategy.py").write_text(STRATEGY_PY.format(created=created, source_note=note))
    joblib.dump(model, out / "model.joblib")
    cfg_dict = cfg.to_dict()
    cfg_dict.setdefault("rank_features", bool(getattr(cfg, "rank_features", True)))
    (out / "config.json").write_text(json.dumps(cfg_dict, indent=2) + "\n")
    (out / "feature_names.json").write_text(json.dumps(names, indent=2) + "\n")
    shutil.copy(_source_file(REPO_ROOT / "run_paper.py"), out / "run_paper.py")
    shutil.copy(_source_file(REPO_ROOT / "docs" / "README_EXPORT.md", REPO_ROOT / "README_EXPORT.md"), out / "README_EXPORT.md")
    shutil.copy(_source_file(REPO_ROOT / ".env.example"), out / ".env.example")
    (out / "requirements.txt").write_text(_requirements(versions))
    shutil.copytree(PACKAGE_DIR, out / "quantsoc_ml", ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    files = list(BUNDLE_FILES) + ["quantsoc_ml/"]
    if data_path is not None:
        long = D.load_prices(data_path)
        long = long[long["symbol"].isin(syms)]
        keep = sorted(long["date"].unique())[-int(recent_days):]
        recent = long[long["date"].isin(keep)].copy()
        recent["date"] = recent["date"].dt.strftime("%Y-%m-%d")
        (out / "data").mkdir()
        recent.to_csv(out / RECENT_DATA, index=False, compression="gzip")
        files.append(RECENT_DATA)
    manifest = {
        "bundle_kind": BUNDLE_KIND,
        "schema_version": SCHEMA_VERSION,
        "created_at": created,
        "package_version": __version__,
        "sklearn_version": versions["scikit-learn"],
        "versions": versions,
        "used_reference_knobs": bool(used_reference),
        "strategy_source_note": note,
        "model_class": type(model).__name__,
        "feature_names": names,
        "rank_features": bool(getattr(cfg, "rank_features", True)),
        "rows_needed": rows_needed(names),
        "symbols": syms,
        "files": files,
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    problems = _scan_dir(out)              # the folder is written in full, then removed if anything looks like a key
    if problems:
        shutil.rmtree(out)
        raise ValueError("export refused, the bundle would contain something that looks like a credential: "
                         + "; ".join(problems))
    return out


def zip_bundle(out_dir, zip_path) -> Path:
    """Zip the bundle folder (top-level folder inside the ZIP = the bundle's name). Skips .env and caches."""
    out, zip_path = Path(out_dir).resolve(), Path(zip_path).resolve()
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(out.rglob("*")):
            rel = p.relative_to(out)
            if p == zip_path or not p.is_file() or p.suffix == ".pyc":
                continue
            if any(part in EXCLUDED_PARTS for part in rel.parts):
                continue
            if p.name.startswith(".env") and p.name != ".env.example":
                continue
            zf.write(p, (Path(out.name) / rel).as_posix())
    return zip_path


def check_zip(zip_path) -> Dict[str, object]:
    """Which required files are present, and that nothing secret-looking is inside. `ok` sums it up."""
    with zipfile.ZipFile(zip_path) as zf:
        names = zf.namelist()
        inner = ["/".join(n.split("/")[1:]) for n in names]
        forbidden = [n for n in inner if n.split("/")[-1] == ".env"
                     or (n.split("/")[-1].startswith(".env") and n.split("/")[-1] != ".env.example")]
        secret_hits: List[str] = []
        env_vals = _env_secret_values()
        for n in names:
            data = zf.read(n)
            secret_hits += [f"{n}: {h}" for h in _bytes_hits(data)]
            if any(v in data for v in env_vals):
                secret_hits.append(f"{n}: contains the value of an APCA_* environment variable")
    missing = [f for f in BUNDLE_FILES if f not in inner]
    package = any(s.startswith("quantsoc_ml/") and s.endswith("paper.py") for s in inner)
    return {"files": len(names), "missing": missing, "forbidden_present": forbidden, "secret_hits": secret_hits,
            "package_included": package, "data_included": RECENT_DATA in inner,
            "ok": not missing and not forbidden and not secret_hits and package}


# --------------------------------------------------------------------------- loading a bundle

@dataclass
class Bundle:
    path: Path
    module: types.ModuleType
    model: object
    config: StrategyConfig
    feature_names: List[str]
    symbols: List[str]
    manifest: dict

    @property
    def source_note(self) -> str:
        return self.manifest.get("strategy_source_note", "source not recorded")


def load_strategy_module(path, name: Optional[str] = None) -> types.ModuleType:
    """Import a strategy.py by path and check it has predict_returns and target_weights."""
    path = Path(path).resolve()
    name = name or f"qsml_strategy_{abs(hash(str(path)))}"
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    for fn in ("predict_returns", "target_weights"):
        if not callable(getattr(module, fn, None)):
            raise ValueError(f"{path} must define a function called {fn}")
    return module


def load_bundle(bundle_dir) -> Bundle:
    """Load and cross-check a bundle folder: config and feature list agree, and the model fits them."""
    import joblib

    d = Path(bundle_dir).resolve()
    if not (d / "strategy.py").is_file():
        raise FileNotFoundError(f"{d} has no strategy.py: export a bundle first, or pass --bundle with its folder")
    cfg = StrategyConfig.from_dict(json.loads((d / "config.json").read_text()))
    names = json.loads((d / "feature_names.json").read_text())
    if list(names) != list(cfg.feature_names):
        raise ValueError(f"feature_names.json {names} does not match the knobs in config.json {cfg.feature_names}")
    manifest = json.loads((d / "manifest.json").read_text()) if (d / "manifest.json").is_file() else {}
    model = joblib.load(d / "model.joblib")
    n_in = getattr(model, "n_features_in_", None)
    if n_in is not None and int(n_in) != len(names):
        raise ValueError(f"model.joblib expects {n_in} features, the bundle lists {len(names)}")
    module = load_strategy_module(d / "strategy.py")
    symbols = list(manifest.get("symbols") or [])
    if not symbols:
        raise ValueError("manifest.json lists no symbols; pass --symbols")
    return Bundle(path=d, module=module, model=model, config=cfg, feature_names=list(names), symbols=symbols,
                  manifest=manifest)
